### ISSUE TITLE
"Element type is invalid" error after starting the app

### ISSUE THREAD

**Issue by thp96** [timomeh/react-native-material-bottom-navigation#103]
Question / Problem

### Actual behavior

I have got the error in both Android and iOS when I copy source code from examples/Playground/App.js.

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
> 
> Check the render method of `BackgroundDecorator`.

### Expected behavior

I would like to run the examples normally and customize my navigation bar.
I can't understand this error!
I have installed react-navigation@1.1.2

**Comment by timomeh** [comment]
Please provide a reproducible example as Expo Snack or GitHub Repo. The create-react-native-app inside `examples/Playground` works.

**Comment by thp96** [comment]
The repo is in github.com/timomeh/react-native-material-bottom-navigation
=> examples/Playground folders.

I copied App.js source code and paste to my component but it got error.

Thank you!

**Comment by timomeh** [comment]
No, I need a reproductible example. Is your app a create-react-native-app so you can simply copy paste it in there? Did you install the dependencies (e.g. expo/vector-icons) from the example? I can't help you without those informations.

Please provide a reproducible example, which I can run on my device and see the error.

**Comment by thp96** [comment]
Sorry, I cant give you my app because it's my company's souce.
I have installed react-navigation@1.1.2, react-native-vector-icons@4.4.6 and react-native-router-flux@3.37.0.
I have copied the all class in the Playground, edit component and Tab's path as my project, but the problems still there. I think I will try another project and fix this issue. Thanks for your reply and please close this issue!

**Comment by timomeh** [comment]
You aren't supposed to share your entire codebase. If you have an issue like this, you need to provide a simple example, which can reproduce the error. This is because your error does not seem to be an bug in the BottomNavigation, but something you've done wrong. It's no problem to do something wrong and get help, but without actual code and without seeing your code, I can't help you.

If you're still experiencing this issue and have a reproducible example, you can share it here and I'm willing to help. But without a example, which reproduces this error, I simple cannot help you.
