### ISSUE TITLE
how to show tabs right to left ?

### ISSUE THREAD

**Issue by ali226281** [timomeh/react-native-material-bottom-navigation#104]
hi , how to show tabs right to left ?

**Comment by timomeh** [comment]
Please open a new issue and fill out the issue template. Is this a feature request? Is this a bug? How does it currently look ("Actual behavior"), and how do you want it to look ("Expected behavior")? Screenshots or other example images would be good. I have no clue how right-to-left languages work and how right-to-left UIs look.
