### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by omi10859** [timomeh/react-native-material-bottom-navigation#105]
here: https://www.npmjs.com/package/react-native-material-bottom-navigation#usage

```
  renderIcon = icon => ({ isActive }) => (
    <Icon size={24} color="white" name={tab.icon} />
  ))
 ```
should be 

```
  renderIcon = icon => ({ isActive }) => (
    <Icon size={24} color="white" name={tab.icon} />
  )

**Comment by timomeh** [comment]
This typo was already fixed a while ago. The readme.md on GitHub is correct. npm has no way of updating the readme.md on their page unless I publish a new version, and I don't want to publish a patch just because of a minor typo in the readme.

Also you didn't fill out the issue template. Please always fill out the issue template if one is provided, in every Repo. If this was a real issue, I'd close it immediately. The Issue Template helps every contributor and saves a lot of time.
