### ISSUE TITLE
Usage with react-native-navigation best practices ?

### ISSUE THREAD

**Issue by MonchiLin** [timomeh/react-native-material-bottom-navigation#115]

**Comment by timomeh** [comment]
Please always provide a description with sufficient informations, if you want an adequate answer.

Stackoverflow is a better place for questions like yours, rather than GitHub Issues. I don't use react-native-navigation, and there's a greater chance that someone on Stackoverflow will find your question and will be able to answer it.

react-native-navigation has a [topic on stackoverflow](https://github.com/wix/react-native-navigation#quick-links) and a [discord](https://discord.gg/DhkZjq2)

I'm going to close this issue since it's no real issue and rather a question for react-native-navigation than the material-bottom-navigation
