### ISSUE TITLE
Invarient VIolation: Element Type is Invalid

### ISSUE THREAD

**Issue by vkiranmaniya** [timomeh/react-native-material-bottom-navigation#118]
I'm getting Invariant VIolation: Element Type is Invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object in the default given example of official documentation.
I'm Using npm 4.0.0 and Node 10.13.0 with react native expo.

**Comment by timomeh** [comment]
That's most likely an error in your code. I can't know where it is, since you didn't fill out the issue template and didn't provide any code snippets.

If you search "[Element Type is Invalid](https://github.com/timomeh/react-native-material-bottom-navigation/issues?utf8=%E2%9C%93&q=Element+Type+is+Invalid)" in the issues of this repository, you will find 3 similar results. Did you check if someone had the same error? Maybe you will find your answer directly.

Because you didn't fill out the issue template, I'm going to close this issue. If you still need help, please open a new issue and fill out the issue template.
