### ISSUE TITLE
How to change the tab background color while it is in active state

### ISSUE THREAD

**Issue by malenchelon** [timomeh/react-native-material-bottom-navigation#136]
how can I change the tab background color while in active state

**Comment by timomeh** [comment]
You can't

**Comment by timomeh** [comment]
Please note: You didn't fill out the issue template (the prefilled text if you open an issue). The issue template always helps every maintainer in every project by having structured reports, informations and generally stay sane. If you submit a issue, always fill out the issue template, if there is one.

I'm going to close this issue since it's not possible and thus a feature request. PRs are welcome.
