### ISSUE TITLE
The navigation prop is missing for this navigator. In react-navigation v3 and v4 you must set up your app container directly.

### ISSUE THREAD

**Issue by KilicSelcuk** [timomeh/react-native-material-bottom-navigation#138]
**Describe the bug**
C:\reactnative2\ornekproje4\node_modules\react-native\Libraries\Core\ExceptionsManager.js:76 Invariant Violation: The navigation prop is missing for this navigator. In react-navigation v3 and v4 you must set up your app container directly. More info: https://reactnavigation.org/docs/en/app-containers.html

This error is located at:
    in Navigator (at renderApplication.js:45)
    in RCTView (at AppContainer.js:109)
    in RCTView (at AppContainer.js:135)
    in AppContainer (at renderApplication.js:39)

**Expected behavior**
****

**Screenshots**
***

**To Reproduce**
****

**Environment**
- React Native Version: last version
- Expo Version (if applicable): no

**Comment by timomeh** [comment]
Your issue is missing important information, e.g. a description what you're actually trying to do and a code snippet. I would advise you to take a look at the [documentation](https://github.com/timomeh/react-native-material-bottom-navigation#documentation) and the whole [readme](https://github.com/timomeh/react-native-material-bottom-navigation/blob/master/README.md).
