### ISSUE TITLE
Set Badge for more than one icon in the bottom bar

### ISSUE THREAD

**Issue by Nazeercs** [timomeh/react-native-material-bottom-navigation#140]
Need Badge for for two icons.now only possible to set badge for only one icon in the bottom bar

**Comment by timomeh** [comment]
Notice: You didn't fill out the issue template. **Always fill out the issue template** if you create a new issue and it has a template.

If you need a special tab, you need to create one yourself. Take a look at https://github.com/timomeh/react-native-material-bottom-navigation/blob/ae325eb468cad26e8089e81f2b0ddfcc50858a33/lib/FullTab.js for how to create your own tab, or if you can customize it.

I'm going to close this issue since it's neither a bug report nor a feature request.
