### ISSUE TITLE
Can you provide a regular version？not use react-native

### ISSUE THREAD

**Issue by adam-zhu-1991** [timomeh/react-native-material-bottom-navigation#20]
I'm doing a small mobile web app and just using normal javascript language, i looking for a long time have not found material bottom navigation javascript plugin , But I want material bottom navigation components and style, so, i hope you can provide a regular version, using normal html/js/css ......

thanks

**Comment by timomeh** [comment]
Thank you for your request. Interesting thought! Unfortunately you can't simply port a react-native component to plain HTML/JS/CSS, since components for the web and react-native components are very different in many aspects.

So, such a component would be a completely new project and I can't easily provide it.

Currently I don't have any project where I could/would need it, so there is no intent for me to write such a component. Maybe someday? But not in the near future, sorry.
