### ISSUE TITLE
suggestion: maybe you can support a no-label version?

### ISSUE THREAD

**Issue by edwardfxiao** [timomeh/react-native-material-bottom-navigation#31]
supporting icon-only might be helpful for a certain amount of people

**Comment by timomeh** [comment]
Usually I would refer to https://github.com/timomeh/react-native-material-bottom-navigation/issues/15#issuecomment-285116249 and say that that's not how the guidelines define the material bottom navigation, **but I changed my mind on this… at least a bit**.

At the moment I can't simply support full customizability, because I tried to be really detailed in my implementation. For example the animations are pixel-perfect, and if I would support something like changing label size (as someone else suggested), the Animations would be totally fucked up.

But after seeing examples of real Apps from Google with the Bottom Navigation (cf. YouTube), I realized they don't use their own BottomNavigation at all. The official Android Libraries for the BottomNavigation aren't really that great, too. I also read/heard good arguments for _not_ using the BottomNavigation as the Guidelines define them.

**So, public service announcement: I decided to provide a much more flexible version.** Yep, that would also include a no-label version. Making a new version has a high priority for me. But please don't expect a new version in the next two or three weeks or so. I'm also a bit involved in my work and social life. 😄 

🎉

**Comment by edwardfxiao** [comment]
really glad to hear that! And sure, take your time😄

**Comment by deadcoder0904** [comment]
Any update ? Gosh, the labels are annoying coz my Labels are pretty big so the animations look a bit weird 😩

**Comment by timomeh** [comment]
I'm busy af at the moment, sorry. Will try to do something soon.

**Comment by deadcoder0904** [comment]
Its OK. No need to be Sorry 😄 
I created my own for my particular use-case
Bdw awesome library just labels are annoying for me 😂 bcz on smaller devices with 5 tabs it looks more weirder
Happy Coding 😃

**Comment by raihanrazi** [comment]
Great work on this! Looking forward to the next release. Cheers

**Comment by danielcdcj** [comment]
I'm interested in having icon-only tab bar too! Looking forward to the next release. Cheers!

**Comment by josephbuchma** [comment]
+1

**Comment by timomeh** [comment]
I am currently (at this moment) doing a big refactor/rewrite of the whole BottomNavigation. I'll include this feature in the upcoming version.

**Comment by timomeh** [comment]
Closed with release of v1.0.0. Check out the docs for [`IconTab`](https://timomeh.gitbook.io/material-bottom-navigation/api-reference/icontab). 🚀
