### ISSUE TITLE
Hide Bottom Navigation After Enter Stack Navigation Screen

### ISSUE THREAD

**Issue by kriptonhaz** [timomeh/react-native-material-bottom-navigation#45]
My Project it's look like this
-Login
--Home Tab 
---Menu
-----Attendance
---Profile
-----Change Password
---Settings

When I tried to enter Attendance menu or Change Password, I want to try to hide the bottom navigation but didn't know how to change these setting. Is there any trick to accomplished that?

**Comment by timomeh** [comment]
That depends on how you use the BottomNavigation. Is it standalone or together with react-navigation?

If you use it together with react-navigation, you should search their documentation on how to hide the BottomNavigation (TabBar) on a specific screen. If you use it standalone, it really depends on your project structure – but I can't help you with that.

Be aware of Issue #42, where someone experienced a bug when hiding the BottomNavigation. I didn't had the time to fix it yet.

Because that's not really a feature or bug of this component, I'm going to close this issue.
